package:
  name: apsw
  version: {{ CONDA_PACKAGE_VERSION }}

source:
  path: ../

build:
  script: python setup.py install

requirements:
  build:
    - git
    - python 2.7.*
  run:
    - sqlite 3.9.2

test:
  requires:
    - python 2.7.*
  commands:
    - python setup.py test

about:
  home: https://github.com/probcomp/bayeslite-apsw
  license: Apache
  license_file: LICENSE
